# FakeNewsDetector Configuration

# API Server Configuration
api:
  host: "0.0.0.0"
  port: 8000
  debug: true
  workers: 4
  timeout: 30

# Database Configuration
database:
  type: "postgresql"
  host: "db"
  port: 5432
  name: "fakedetector"
  user: "fakedetector"
  password: "fakedetector"
  connect_timeout: 5
  pool_size: 10

# Analysis Configuration
analysis:
  # Statistical Analysis Settings
  statistical:
    enabled: true
    readability_algorithms: ["flesch_kincaid", "coleman_liau"]
    minimum_text_length: 100
    fact_opinion_ratio_weight: 0.3
    readability_weight: 0.2
    word_frequency_weight: 0.5

  # Linguistic Analysis Settings
  linguistic:
    enabled: true
    sentiment_analysis: true
    emotional_markers_detection: true
    manipulative_constructs_detection: true
    sentiment_weight: 0.3
    emotional_markers_weight: 0.3
    manipulative_constructs_weight: 0.4

  # Semantic Analysis Settings
  semantic:
    enabled: true
    contradiction_detection: true
    coherence_analysis: true
    key_themes_extraction: true
    model_name: "ru_core_news_sm"
    contradictions_weight: 0.4
    coherence_weight: 0.3
    key_themes_weight: 0.3

  # Structural Analysis Settings
  structural:
    enabled: true
    journalism_standards_checking: true
    structure_quality_analysis: true
    violations_detection: true
    journalism_standards_weight: 0.4
    structure_quality_weight: 0.4
    violations_weight: 0.2

# Logging Configuration
logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
